### ISSUE TITLE
running elm-format doesn't reload file automatically

### ISSUE THREAD

**Issue by surfncode** [elm-community/Elm.tmLanguage#5]
I have to switch tab in sublime to have the file reloaded and view the formatted result. It doesn't matter if the setting elm_format_on_save is set to true or not. This happens whether elm-format is run automatically during save or from the command panel.

**Comment by sentience** [comment]
I’m not able to reproduce this issue with the current release.

**Comment by FMCorz** [comment]
Same here, this may help:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/Elm Language Support/elm_show_type.py", line 226, in on_activated_async
    view_load(view)
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/Elm Language Support/elm_show_type.py", line 210, in view_load
    load_from_oracle(view.file_name())
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/Elm Language Support/elm_show_type.py", line 168, in load_from_oracle
    os.chdir(project.working_dir)
FileNotFoundError: [Errno 2] No such file or directory: ''
```
